### ISSUE TITLE
/upload is erroring with 404 not found

### ISSUE THREAD

**Issue by jywarren** [publiclab/spectral-workbench#641]
https://spectralworkbench.org/upload

https://github.com/publiclab/spectral-workbench/blob/main/config/routes.rb#L40 - not sure why, the route looks good

**Comment by jywarren** [comment]
Strange, @icarito doesn't see this:

![image](https://user-images.githubusercontent.com/24359/120227741-c0d2aa00-c217-11eb-89a2-de4bd7845c1d.png)

**Comment by jywarren** [comment]
Tested multiple times more and i'm still unable to access it from my chromebook. will try other devices. Sebastian still able to access it.

**Comment by jywarren** [comment]
And it works fine in GitPod on my chromebook...

**Comment by jywarren** [comment]
Same 404 from Android phone chrome browser:

![Screenshot_20210531-143152](https://user-images.githubusercontent.com/24359/120230306-0ba2f080-c21d-11eb-95a2-a30c9351e8b8.png)

**Comment by norenTM** [comment]
Is this going to be addressed soon? I have a project due very soon and I'm worried that I will have incomplete data. I can't get the upload page to load on any device.

**Comment by icarito** [comment]
Hello,
Yes after some discussion and looking at the feedback, we've decided to
rollback into the previous version tonight.
Please excuse the disruption in the regular functionality of Spectral
Workbench.
Regards,
--
Sebastian Silva
System Administrator at Public Lab

**Comment by icarito** [comment]
We've rolled back to a previous version. Please let us know if you continue to have problems.

**Comment by norenTM** [comment]
Logging in results in a 404 😅

**Comment by norenTM** [comment]
> Attempting to log in with any service results in a 404 😅

This has been resolved now, I assume due to time. Thank you very much for your efforts, all 404-related bugs (/upload, downloading files) have all been eradicated.

**Comment by jywarren** [comment]
Thank you for the extra checks @norenTM -- much appreciated. We have been simultaneously dealing with some very high bot activity on PublicLab.org and trying to mitigate downtime in relation to that.

For folks working on this issue, we rolled back but the error is still visible at https://stable.spectralworkbench.org/upload (our staging server) -- compare to https://spectralworkbench.org/upload which now works post-rollback. 

NOTE: sessions and cookies make logging into both from the same browser tough. Try logging into https://stable.spectralworkbench.org/upload from an incognito tab, and https://spectralworkbench.org/upload from a regular tab. 

I'm really mystified at what could be causing this. Will look at any possible routing changes that could possibly affect this. Also CC'ing @waridrox just for a heads up!

**Comment by jywarren** [comment]
Could Bootsnap be involved here? It provides a lot of caching.

**Comment by jywarren** [comment]
OK seems the big upgrade in #539  is likely to be the issue - it removed default routing at:

![image](https://user-images.githubusercontent.com/24359/121730701-0c117600-cabe-11eb-825b-144d829e9a8e.png)

https://github.com/publiclab/spectral-workbench/commit/98dbde7a881788f7bd48db59eee616d6de70054b#diff-959bc9abc46a55332bb64d5155a79323afa75a50ec1a2137ddd22d926f62c6c5L193

I bet we had really been relying on it. We can use GitPod to ensure routing works correctly and that should resolve this. 

Any upload issues are likely to have a similar issue!

**Comment by jywarren** [comment]
OK, update -- i wasn't able to reproduce this in gitpod -- it shows upload fine:

![image](https://user-images.githubusercontent.com/24359/122106632-2d3cd400-cde8-11eb-9676-1d1e262e2e91.png)

Looking deeper!

**Comment by jywarren** [comment]
OK, on stable, I can see it happening. And I think we may be GETTING a 500 error, but for some reason be SEEING a 404. I confirmed it's a 404 in the Chrome console. But, on the server side, i see:

```
I, [2021-06-15T22:10:48.491057 #349]  INFO -- : [e7fafce2-2dc2-436d-89e6-68c583d81957] Redirected to https://stable.spectralworkbench.org/upload
I, [2021-06-15T22:10:48.491247 #349]  INFO -- : [e7fafce2-2dc2-436d-89e6-68c583d81957] Completed 302 Found in 34ms (ActiveRecord: 29.6ms)
I, [2021-06-15T22:10:48.516115 #349]  INFO -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4] Started GET "/upload" for 72.92.236.166 at 2021-06-15 22:10:48 +0000
I, [2021-06-15T22:10:48.517812 #349]  INFO -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4] Processing by SpectrumsController#new as HTML
D, [2021-06-15T22:10:48.520521 #349] DEBUG -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   ESC[1mESC[36mUser Load (0.8ms)ESC[0m  ESC[1mESC[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1ESC[0m
D, [2021-06-15T22:10:48.521696 #349] DEBUG -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   ESC[1mESC[36mCACHE User Load (0.2ms)ESC[0m  ESC[1mESC[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1ESC[0m  [["id", 1], ["LIMIT", 1]]
I, [2021-06-15T22:10:48.524874 #349]  INFO -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   Rendering layouts/application.html.erb
I, [2021-06-15T22:10:48.525478 #349]  INFO -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   Rendering spectrums/new.html.erb within layouts/application
I, [2021-06-15T22:10:48.530425 #349]  INFO -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   Rendered spectrums/_new_image.html.erb (0.7ms)
D, [2021-06-15T22:10:48.531328 #349] DEBUG -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   ESC[1mESC[36mCACHE User Load (0.2ms)ESC[0m  ESC[1mESC[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1ESC[0m  [["id", 1], ["LIMIT", 1]]
D, [2021-06-15T22:10:48.532618 #349] DEBUG -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   ESC[1mESC[36mCACHE User Load (0.3ms)ESC[0m  ESC[1mESC[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1ESC[0m  [["id", 1], ["LIMIT", 1]]
D, [2021-06-15T22:10:48.589230 #349] DEBUG -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   ESC[1mESC[36mSpectrum Load (19.0ms)ESC[0m  ESC[1mESC[34mSELECT spectrums.id, spectrums.created_at, spectrums.user_id FROM `spectrums` INNER JOIN `tags` ON `tags`.`spectrum_id` = `spectrums`.`id` WHERE `spectrums`.`user_id` = 1 AND (tags.name = ('calibration') OR tags.name LIKE ('linearCalibration:%')) ORDER BY spectrums.created_at DESCESC[0m
D, [2021-06-15T22:10:48.789492 #349] DEBUG -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   ESC[1mESC[36mSpectrum Load (189.3ms)ESC[0m  ESC[1mESC[34mSELECT `spectrums`.* FROM `spectrums` INNER JOIN `tags` ON `tags`.`spectrum_id` = `spectrums`.`id` WHERE `spectrums`.`id` IN (120774, 112148, 92538, 89900, 89557, 88735, 88734, 88733, 88732, 88731, 88730, 88729, 88728, 85787, 83326, 82252, 82252, 82251, 79087, 73760, 72806, 72366, 72365, 72364, 72360, 71686, 71243, 71081, 71075, 70824, 70808, 70790, 70771, 70770, 70769, 70768, 70723, 70723, 70695, 69973, 69704, 69703, 69662, 69662, 68681, 68680, 68588, 68585, 68577, 66713, 66713, 63935, 59744, 59744, 58942, 58236, 55077, 55067, 38256, 36143, 36006, 16070, 16069, 14917, 14182, 12305, 12106, 12067, 12065, 10863, 10219, 9590, 8443, 8427, 8426, 8425, 8424, 8423, 8421, 8420, 8418, 8416, 8000, 7999, 7998, 7957, 7950, 7949, 7948, 5708, 5162, 5161, 5160, 5159, 5158, 5157, 5156, 5155, 5154, 5153, 5152, 5151, 5150, 5148, 5147, 5146, 5145, 5144, 5143, 5142, 5130, 5129, 5128, 5127, 5126, 5125, 5124, 4780, 4778, 4777, 4776, 4772, 4769, 4768, 4767, 4766, 4763, 4762, 4737, 4735, 4734, 4732, 4731, 4729, 4726, 4717, 4711, 4705, 4700, 4699, 4690, 4631, 4520, 4038, 1980, 1739, 1714, 1390, 1175, 1033, 800, 800, 707, 707, 707, 596, 595, 595, 591, 555, 555, 551, 551, 482, 482, 475, 442, 442, 442, 413, 413, 413, 408, 408, 408, 408, 384, 377, 374, 371, 364, 351, 351, 333, 320, 101, 46, 45, 22, 21, 21)ESC[0m
D, [2021-06-15T22:10:48.918450 #349] DEBUG -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   ESC[1mESC[36mCACHE User Load (0.1ms)ESC[0m  ESC[1mESC[34mSELECT  `users`.* FROM `users` WHERE `users`.`id` = 1 LIMIT 1ESC[0m  [["id", 1], ["LIMIT", 1]]
D, [2021-06-15T22:10:48.922459 #349] DEBUG -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   ESC[1mESC[36mTag Load (0.6ms)ESC[0m  ESC[1mESC[34mSELECT `tags`.* FROM `tags` WHERE `tags`.`id` IN (NULL, NULL)ESC[0m
I, [2021-06-15T22:10:48.923419 #349]  INFO -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   Rendered spectrums/new.html.erb within layouts/application (397.8ms)
I, [2021-06-15T22:10:48.923523 #349]  INFO -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   Rendered layouts/application.html.erb (398.5ms)
I, [2021-06-15T22:10:48.923834 #349]  INFO -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4] Completed 500 Internal Server Error in 406ms (ActiveRecord: 212.3ms)
F, [2021-06-15T22:10:48.924948 #349] FATAL -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   
F, [2021-06-15T22:10:48.925007 #349] FATAL -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4] ActiveRecord::RecordNotFound (Couldn't find all Tags with 'id': (all, {:conditions=>{:user_id=>1, :name=>"calibration"}, :include=>:spectrum, :limit=>20, :order=>"id DESC"}) (found 0 results, but was looking for 2).):
F, [2021-06-15T22:10:48.925049 #349] FATAL -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4]   
F, [2021-06-15T22:10:48.925109 #349] FATAL -- : [f3ff1510-fdd5-47a9-b781-baa27dd36dc4] app/models/user.rb:100:in `tag'
[f3ff1510-fdd5-47a9-b781-baa27dd36dc4] app/views/spectrums/new.html.erb:113:in `_app_views_spectrums_new_html_erb__2650622626532582424_70304386915120'
```

**Comment by jywarren** [comment]
Key section:

```
Completed 500 Internal Server Error in 406ms (ActiveRecord: 212.3ms)
ActiveRecord::RecordNotFound (Couldn't find all Tags with 'id': (all, {:conditions=>{:user_id=>1, :name=>"calibration"}, :include=>:spectrum, :limit=>20, :order=>"id DESC"}) (found 0 results, but was looking for 2).):
app/models/user.rb:100:in `tag'
```

**Comment by jywarren** [comment]
https://github.com/publiclab/spectral-workbench/blob/afe7c986bbdd871d76ec162dd1d8896b2a165f07/app/models/user.rb#L98-L104

**Comment by jywarren** [comment]
I bet we can't reproduce in GitPod because it's database dependent. Like, recent calibrations or something!

**Comment by jywarren** [comment]
And, we should figure out why we're seeing a 404 instead of a 500!

**Comment by jywarren** [comment]
Yes, reproducing this will require having a spectrum tagged "calibration" in your profile! The fix, i hope, is at #651.
